spring:
  application:
    name: retail-product-api
  data:
    mongodb:
      uri: mongodb+srv://mongo_user:Target2250@clustermumbai-9xicj.mongodb.net/Product?retryWrites=true&w=majority

redsky:
  uri: https://redsky.target.com
